# Generated by Django 5.0 on 2024-02-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0002_alter_register_phonenumber_alter_register_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='Register',
        ),
    ]
